name: CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set up environment
        run: |
          echo DATABASE_URL=postgresql://postgres:postgres@localhost:5433/test > .env.test
          echo JWT_SECRET=test_secret >> .env.test

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          curl -fsSL https://cli.railway.app/install.sh | sh
          railway up
